[package]
name = "popgetter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.73"
geojson = "0.24.1"
polars = "0.32.1"
reqwest = "0.11.20"
tempfile = "3.8.0"
tokio = {version = "1.32.0", features = ["full"]}
zip = "0.6.6"
